### ISSUE TITLE
Integration 'goecharger' not found

### ISSUE THREAD

**Issue by Tscherno** [cathiele/homeassistant-goecharger#1]
Servus,

Du hast genau das gebaut was ich gerade brauche :)

Leider schmeisst er nach dem Kopieren folgenden Fehler:

2019-12-26 14:52:16 ERROR (MainThread) [homeassistant.components.hassio] Component error: goecharger - Integration 'goecharger' not found.
  File "", line 219, in _call_with_frames_removed
  File "/config/custom_components/goecharger/__init__.py", line 9, in 
    from goecharger import GoeCharger
ModuleNotFoundError: No module named 'goecharger'

**Comment by cathiele** [comment]
Moin,

es sieht so aus, als ob der "goecharger" import nicht gefunden wurde. normalerweise wird die automatisch heruntergeladen (weil in der manifest.json definiert) ich nutze home-assistant im Docker (also nicht hass.io) 
* wie sieht denn deine Umgebung aus?
* Was wird beim start von homeassistant geloggt?
* Wie hast du die Erweiterung genau installiert?

**Comment by Tscherno** [comment]
Hat sich eben erledigt. Ein kompletter Reboot war dazwischen und das hat es vielleicht gelöst... Jetzt gehts auf jeden Fall, danke :)

**Comment by cathiele** [comment]
Ok, wenn du noch Fehler findest, oder dir Funktionen  fehlen mache gerne ein Ticket auf :)
