### ISSUE TITLE
SwitchDevice is deprecated

### ISSUE THREAD

**Issue by BertilJ** [cathiele/homeassistant-goecharger#13]
Hi

Great work on this component, takes away a lot of effort creating all the rest calls through templating since I don't do Python very well!! :)

I just saw a message in my log though:

```
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125
Integration: Switch (documentation, issues)
First occurred: 10:10:33 AM (1 occurrences)
Last logged: 10:10:33 AM

SwitchDevice is deprecated, modify GoeChargerSwitch to extend SwitchEntity
```

/Andreas

**Comment by cathiele** [comment]
thank you for reporting this. Will look into it.
