### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by crohot** [cathiele/homeassistant-goecharger#14]
Hallo, ich probiere es mal mit einem neuen Issue. 
Ich bekomme folgende Fehlermeldung:

`Invalid config for [goecharger]: [input_number] is an invalid option for [goecharger]. Check: goecharger->goecharger->input_number. (See /config/configuration.yaml, line 68).
`
Meine Einträge in der config sehen aber so aus, wie im Beispiel empfohlen:

goecharger:
  host: 192.168.xx.yy
  serial: ´001234´
  
  input_number:
    goecharger_charge_limit:
      name: Charge limit (kWh)
      min: 0
      max: 10
      step: 1

input_select:
  goecharger_max_current:
    name: Max current
    options:
      - 8
      - 10
      - 12
      - 14

(natürlich mit der passenden IP und S/N)

Was mache ich denn falsch?

**Comment by cathiele** [comment]
Ohne es genau geprüft zu haben, passt die Einrückung in der config-datei? input_number muss auf selber Höhe wie goecharger stehen. Es darf nicht tiefer eingerückt sein.

**Comment by crohot** [comment]
Ich kann es leider nicht 1 zu 1 posten aber ja, die Einrückungen sehen so aus wie im Bsp.
Bei serial gehören doch diese ' Anführungszeichen hin, oder? Ich hatte auch mal ` und ´ ausprobiert.

**Comment by cathiele** [comment]
du kannst deine Config so hier einfügen:
erste Zeile : "```" dann in den Folgezeilen deine Konfiguration dann wieder "```"  dann sollte das hier richtig angezeigt werden.

Die einfachen ' sind die richtigen alternativ gehen auch die " ("normale" doppelte)

**Comment by crohot** [comment]
![goecharger2](https://user-images.githubusercontent.com/64893566/85389897-5796e100-b548-11ea-92d6-5a4c2b7856f2.png)

Mit den Quotes habe ich keinen Erfolg, aber dafür mit der configuration.yaml - Siehe Bild. Danke!

**Comment by cathiele** [comment]
Moin, funktioniert es inzwischen bei dir, oder ist der Punkt weiterhin offen?

**Comment by cathiele** [comment]
Wenn das weiterhin offen ist bitte das wieder auf machen bitte.
