### ISSUE TITLE
Setup fails if charger offline on start

### ISSUE THREAD

**Issue by maulwuff** [cathiele/homeassistant-goecharger#2]
When the charger is offline when starting home assistant, I found this in my log:

```
2020-04-09 21:43:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component goecharger
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
...
```

go-e will also not show up any time later. I have to restart HA, which drops all torque values, unfortunately. 
As the charger is a mobile charger, it is rather common for me, that it is not online that often. Do you think there is a way to make the component reboot-safe?

**Comment by cathiele** [comment]
Will look into it. Thanks for the bugreport. My charger is always online so i did not notice it until Not.

**Comment by cathiele** [comment]
@maulwuff  please verify if it works now with the current version of the master branch

**Comment by maulwuff** [comment]
works fine. thanks! :+1: 
- switches to unknown if charger goes offline
- comes back up with all values when charger is pluged in again.

only issue when going offline is the automation for Amps selector:

`Invalid option: 0 (possible options: 6, 10, 16, 20, 24, 32)`
it is only a warning though.

The last version produced 23MB of ha.log over the last night :scream: - much better now :)

**Comment by cathiele** [comment]
Fixed the min amp value to 6 on disconnected charger. @maulwuff please chef if that `Invalid option`-warning is gone please.

**Comment by maulwuff** [comment]
Now HA behaves weird.
But what happened is, that the select field is fine now, and triggers the automation to set the chargers value, which fails with different errors.

On the first try:
```
goecharger: from user: set max current on charger based on input select: Error executing script. Unexpected error for call_service at pos 1: HTTPConnectionPool(host='192.168.0.107', port=80): Max retries exceeded with url: /mqtt?payload=amp=6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff21b54d6d0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

in another try I got no error at all, in a third try I got
```
TimeoutError: [Errno 110] Operation timed out
```
after that, I got a charger with different serial number showing up ...
After HA restart it showed the error from the first try again.

Maybe its better/easier to revert to the 0-POST again and add a condition to the automation script, which checks value > 0?
like 
```
condition: numeric_state
entity_id: input_select.goecharger_max_current
above: '0'
```

This makes sense 
- for the charger going offline, triggering itself, and 
- to prevent invalid values posted to the charger

For this to work, we need an invalid value, else we can't filter it out in the automation.

**Comment by cathiele** [comment]
Thats for testing it. I reverted for now the last fix. so now it will be "0" on disconnected chargers. still i have to handle errors if someone is setting values on a disconnected charger. I will think about it but for now your solution with the condition it the best we have.

**Comment by maulwuff** [comment]
Auf dem Klo hat man doch noch immer die besten Ideen. :-D
 Was ich vorgeschlagen habe, kann nicht funktionieren. Wenn beim offline gehen wieder 0 ans select geliefert wird, sind wir wieder bei der Warning vor dem fix. 
Wenn der Charger 0 nicht akzeptiert, würde ich es dennoch als Wert in die select-Liste nehmen. 
Dann wird das select auf 0 gesetzt, wenn er offline geht. 
Weiter würde ich die condition in die automation rein nehmen, damit er nicht in den timeout läuft. 
 
Einziger Nachteil: Man kann 0 in der Oberfläche setzen, wenn er online ist, das wird aber dann nicht verarbeitet. Es ändert sich am Charger gar nichts. Ob der User das dann erwartet hätte .... 

Manuelle call service Tests mit dem Schuko-Kabel (möglich 6-16) zeigen, dass er bei Werten unter 6 auf jeden Fall runter schaltet, was dann konträr zum Verhalten über die Gui wäre:  
- bei 32 stellt er sich von 6 auf 16.
- bei 0 stellt er sich von 16 auf 6.
- bei -2 stellt er auch auf 6.
- bei 8 geht er auf 8
 
Von daher würde ich lieber die Warnung fürs select in Kauf nehmen und eine konsistente Gui ohne falsche Werte-Auswahl haben, die dann doch nicht gesendet wird.

**Comment by cathiele** [comment]
Ich glaube bzgl. des Offline gehen des Chargers müssen wir etwas gründlicher vor der Umsetzung nachdenken. Ggf. ist es auch sinnvoll einzelne Werte zu behalten wenn der Charger Offline ist. 

Hat alles Vor- und Nachteile. Ich denke z.B. an den Zählerstand der in Summe geladenen kWh. Wenn der Wert gespeichert wird entstehen z.B. im Diagramm keine "zacken". 

Wenn das für dich erstmal so passt ist belasse ich es erstmal dabei. 

Danke nochmal fürs testen :)

**Comment by maulwuff** [comment]
Mit Zacken habe ich keine Probleme, die hab ich von TorquePro schon reichlich :-)

Aktuell ist es noch so, dass die Sensoren mit falscher Seriennummer auftauchen, wenn der Charger beim Start von HA offline ist. Dann muss ich ihn anstecken, HA neu starten und dann kommen die richtigen Nummern. Das ist reproduzierbar.
Die falsche ist zB sensor.goecharger_4234_adapter
Ich weiß nicht wie "persönlich" die Nummer ist, meine ist 6stellig.

**Comment by cathiele** [comment]
Eine Frage dazu. Hast du die Nummer so konfiguriert: ˋserial: '001234'` durch die führenden 0 kann das sonst als Zahl interpretiert werden. Robuster ist es in dem Fall wohl, wenn ich die Seriennummer auf 6 Stellen auffüllen würde..

**Comment by maulwuff** [comment]
Meine richtige Seriennummer lautet
 `sensor.goecharger_01xxxx_adapter`

In der config steht: 
```
goecharger:
  host: 192....
  serial: 01xxxx
```

ich probiers mal mit Anführungszeichen.

**Comment by crohot** [comment]
Hallo @cathiele , vielen dank für diese schöne Arbeit!
Leider bekomme ich ein paar Fehlermeldungen bei der Umsetzung:
 _Component error: goecharger - Integration 'goecharger' not found._
und
 _Error loading custom_components.goecharger. Make sure all dependencies are installed
 ModuleNotFoundError: No module named 'goecharger'_

Hast Du eine Idee, was ich falsch mache? Ich bin blutiger Anfänger in Sachen Home Assistant...
Danke!
