### ISSUE TITLE
Do not zero sensors at no reading

### ISSUE THREAD

**Issue by BertilJ** [cathiele/homeassistant-goecharger#20]
I am having challenges with using utility meters together with the kwh sensors. Does not matter which I am using, both gives 0 values on and off probably due to the api not responding fast enough. This is causing the utility meters to go crazy, eg reading from current session charged is 10.3 kwh, but the utility meter that is consuming that value gives 255 kwh.

Proposal is to not have the sensors to report 0 when not getting a new update, but rather stay on current value until new actual value is received.

I have set up some rest sensors to test this and the box does not seem to report 0 on and off, but sometimes the api does not report all values.

**Comment by cathiele** [comment]
Will look into this. How can i test it? is it sufficient to disconnect the charger and see if the old values still are used in HA?

**Comment by BertilJ** [comment]
Sorry for late response.

I don't exactly know what happens with the api call if the charger is completly disconnected. But I'm guessing for test purposes if you would send null as a an update for the sensor, the current behaviour would be to set the sensor to 0 and my proposed solution would be that if value is null, i.e not existing there shouldn't be an update to the sensor, the sensor should keep current value.

**Comment by cathiele** [comment]
@BertilJ please check the master branch or version 0.12.0 via hacs solves this for you.

**Comment by TheFitzZZ** [comment]
Will also test. @cathiele thank you so much for your great work!

**Comment by TheFitzZZ** [comment]
Still happening for me - updated to 0.12.0, restarted my HA

![image](https://user-images.githubusercontent.com/13013440/96267797-8b4eb880-0fc8-11eb-8a9d-88d7bb72dfc3.png)

**Comment by cathiele** [comment]
ok, thank you for testing. I will try to reproduce it again

**Comment by maulwuff** [comment]
I get the same drops to 0 on all values. I assumed it is because of loosing wifi connection, maybe give that a try?

**Comment by TheFitzZZ** [comment]
> I get the same drops to 0 on all values. I assumed it is because of loosing wifi connection, maybe give that a try?

I'd suspect the same thing, since my Charger also drops off quite often unfortunately.

**Comment by cathiele** [comment]
Finally i had time to check this issue again. Please update to version 0.14.0 and comment here if it is still a problem.

**Comment by maulwuff** [comment]
As the fix is already from October 2020 it was present in my last charging session when I already had updated via HACS. I had no drops to 0 in this session. Already wondered what was going on, as no such fix was announced ;-)

**Comment by cathiele** [comment]
I now found a way to reproduce it here with adding a firewall DROP-rule to my raspberry with homeassistant:

```iptables -A OUTPUT -p tcp --dport 80 -d <chargerip> -j DROP```

and deleting it with:

```iptables -D OUTPUT -p tcp --dport 80 -d <chargerip> -j DROP```

so i hope i can debug this now more easily.

**Comment by cathiele** [comment]
Please test Version 0.15.0

**Comment by TheFitzZZ** [comment]
Still great after 24h. For me this is solved :-) Thank you!

![image](https://user-images.githubusercontent.com/13013440/117585482-e685fb00-b112-11eb-839c-aa3f2994fb20.png)

**Comment by cathiele** [comment]
Gut Ding will Weile haben ¯\_(ツ)_/¯
