### ISSUE TITLE
Add as hacs default repository

### ISSUE THREAD

**Issue by cathiele** [cathiele/homeassistant-goecharger#25]

**Comment by cathiele** [comment]
Requirements to get accepted into hacs-default list: https://hacs.xyz/docs/publish/include

**Comment by maulwuff** [comment]
is this still open? I can't find goechager in hacs.

**Comment by Bouni** [comment]
I started to get this integration into HACS by adding the required icons [see PR2394](https://github.com/home-assistant/brands/pull/2394) and adding it to wheels-custom-integrations [see PR358](https://github.com/home-assistant/wheels-custom-integrations/pull/358)

Not sure if everything is correct but we'll see 😄

**Comment by maulwuff** [comment]
> is this still open? I can't find goechager in hacs.

I managed to get it working by adding a custom repository to HACS: https://hacs.xyz/docs/faq/custom_repositories/
Settings in the configuration.yml is still needed.

**Comment by Bouni** [comment]
@maulwuff Its absolutely possible to add it as custom repo, thats what most likely all of us do at the moment, but it would be so much nicer to have this available from the HACS store 😎

**Comment by Bouni** [comment]
@cathiele 

Ok, my two PR's in [wheels-custom-integrations](https://github.com/home-assistant/wheels-custom-integrations/pull/358) and [brands](https://github.com/home-assistant/brands/pull/2394) are merged.

So according to the [docs](https://hacs.xyz/docs/publish/include) everything is prepared for you to open the PR for getting this into the default repo:

- [x] Check Brands
- [x] Check Manifest
- [x] Check hassfest
- [x] Check HACS -> We'll see :wink:
- [x] Check HACS Manifest
- [x] Check Info
- [x] Check Fork
- [x] Check Archived
- [x] Check Owner -> This is why you have to submit the PR yourself
- [x] Check Repository
- [x] Check Wheels
- [x] Lint jq -> We'll see 
- [x] Lint sorted -> We'll see

**Comment by cathiele** [comment]
Just created https://github.com/hacs/default/pull/895

@Bouni thanks again for your support!

**Comment by cathiele** [comment]
@Bouni i still need two more reviews for the integration in HACS, any idea how i can get reviewers for  my PR?

**Comment by cathiele** [comment]
now its merged in hacs 👍
