### ISSUE TITLE
Temperature from correct registers

### ISSUE THREAD

**Issue by drivingmx** [cathiele/homeassistant-goecharger#30]
It seems, that "tmp" isn't the right register for temperature values.
tma is an array of the four build in sensors.
https://github.com/goecharger/go-eCharger-API-v1/issues/6#issue-702531026

**Comment by cathiele** [comment]
WIP: Fixed in library release [0.0.15](https://github.com/cathiele/goecharger/releases/tag/0.0.15)

**Comment by cathiele** [comment]
Maybe in PR #34 it is working already. 

My solution at the moment: added 4 new  sensor values (```charger_temp0``` - ```charger_temp3```). Chargers with older FWs will still be able to be used in this way.
