### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'goecharger'.

### ISSUE THREAD

**Issue by Bouni** [cathiele/homeassistant-goecharger#33]
Please release a new version, preferably 0.13.0 to get my already merged PR #31 integrated and prevent HA from printing the error message:

`No 'version' key in the manifest file for custom integration 'goecharger'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'goecharger'
`

**Comment by cathiele** [comment]
done (0.13.0)
