### ISSUE TITLE
Problem with 0.19 with multiple chargers

### ISSUE THREAD

**Issue by michis0806** [cathiele/homeassistant-goecharger#37]
Hi @cathiele ,

thanks for your great work and the recent implementation of multiple charge points this week. 

I just updated to the latest 0.19 and want to give you some feedback. 
(I used HACS to install the new version of the component). My config is

```
goecharger:
  chargers:
    - name: goe_dgar
      host: 192.168.x.y
    - name: goe_mgar
      host: 192.168.x.z

```
I restarted home assistant and found some new entities. The old ones did not disappear so I deleted them. The new naming-scheme seems less specific than the old one. The "goecharger_SERIAL"-prefix is missing so sensor.goecharger_SERIAL_charger_max_current became simply sensor.charger_max_current, sensor.goecharger_SERIAL_car_status became sensor.status which is very generic ;).

My main problem is, that I can only find a switch-entity for my first charger. That was named switch.goecharger_SERIAL_allow_charging in the old implementation. Now I can only find switch.SERIAL2 but no switch for my first charger.

Maybe I made a mistake in setup?

Thanks!
Michael

**Comment by michis0806** [comment]
Quick update: I completely deleted the integration from HACS and removed the config-part. Restarted. installed the integration from HACS again. Added one Charger. Restarted. Added second charger. 

Now both chargers are visible but the entities are still without the goecharger_SERIAL prefix...

Thanks
Michael

**Comment by cathiele** [comment]
Thanks for reporting this. will look into it... @michis0806 could you try 0.18 please with the same config?

**Comment by michis0806** [comment]
Hi @cathiele, I just deinstalled 0.19 and installed 0.18. No change in the naming.

**Comment by cathiele** [comment]
last option without checking the code: 0.19.0 but setup via config flow and not configuration.yaml.

**Comment by cathiele** [comment]
i can reproduce it

**Comment by michis0806** [comment]
Okay, I deinstalled go-e completely, purged goe entries from .storage/core.* and removed the entries from configuration.yaml. Then I restarted, installed go-e 0.19 from HACS and tried to set it up with the integration-workflow. I get the following errors:

<img width="635" alt="Bildschirmfoto 2021-05-14 um 15 25 51" src="https://user-images.githubusercontent.com/11705647/118277851-8c49b900-b4c9-11eb-92cf-df57a1d333d7.png">
<img width="345" alt="Bildschirmfoto 2021-05-14 um 15 26 01" src="https://user-images.githubusercontent.com/11705647/118277857-8d7ae600-b4c9-11eb-9981-4b91d94dfd51.png">
<img width="492" alt="Bildschirmfoto 2021-05-14 um 15 27 54" src="https://user-images.githubusercontent.com/11705647/118277859-8d7ae600-b4c9-11eb-8f56-7e3bc7358043.png">

**Comment by cathiele** [comment]
@michis0806  please test version 0.20.0

**Comment by cathiele** [comment]
> @michis0806 please test version 0.20.0

Sorry, i mean 0.21.0

**Comment by michis0806** [comment]
Setup worked well, now. Entity-naming is solved. But now, the "switch" is  missing again ;)

**Comment by cathiele** [comment]
yes.. sorry, maybe i should setup some tests and a GithubAction Pipeline.... :-)

**Comment by michis0806** [comment]
;)
And I think the goecharger.set_max_current is broken. It doesn't accept any parameters

```
service: goecharger.set_max_current
  data:
    charger_name: 031132
    max_current: 16

```
leads to

`Message malformed: Service goecharger.set_max_current data does not match format <domain>.<name> for dictionary value @ data['action'][0]['service']
`

**Comment by michis0806** [comment]
Perfect! Works without any problems now ;)
Thanks for your help!
