### ISSUE TITLE
Statistic support (energy dashboard)

### ISSUE THREAD

**Issue by yonie1** [cathiele/homeassistant-goecharger#43]
Would it be possible to add support for the new statistic feature (to be able to add the charger to the new energy dashboard)?
All it takes is to add the last_reset and state_class property to the energy counter.
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by cathiele** [comment]
Will look into this feature

**Comment by cathiele** [comment]
Should work in version 0.23.0
