### ISSUE TITLE
integration stopped working

### ISSUE THREAD

**Issue by stepir** [cathiele/homeassistant-goecharger#46]
Hi 

I don't think I have done anything particular and only afterward upgrade my v2 charger to  041 fw.

The integration stopped working and when reinstalling and configuring I'm also getting the same error:

This error originated from a custom integration.

```
Logger: custom_components.goecharger
Source: custom_components/goecharger/__init__.py:91
Integration: go-eCharger (documentation, issues) 
First occurred: 1:31:32 AM (1 occurrences) 
Last logged: 1:31:32 AM

Unable to fetch state for Charger 038266
```

then 

```
Logger: homeassistant.setup
Source: setup.py:310 
First occurred: 1:31:32 AM (2 occurrences) 
Last logged: 1:31:32 AM

Unable to prepare setup for platform goecharger.sensor: Platform not found (cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
```

your help is appreciated

thanks

**Comment by cathiele** [comment]
I am using the 41 Firmware without Problems. Do you have the latest Plugin version 0.23? Are you using the latest Home Assistant Version? (2021.9?)

**Comment by stepir** [comment]
Thanks updating ha and the plug-in did the trick
