### ISSUE TITLE
Cable lock/switch entity

### ISSUE THREAD

**Issue by jmtatsch** [cathiele/homeassistant-goecharger#51]
**Is your feature request related to a problem? Please describe.**
I would like to lock the cable of my charger while I am away but unlock it when I am close by for fast switching to another cable for a friend.

**Describe the solution you'd like**
I would love to have a lock or switch entity to engage or disengage the lock via an automation.

**Describe alternatives you've considered**
Do this by app which is annoying because my friend that uses the other cable type needs to call me to start the process.

**Additional context**
`ust` seems to be the appropriate api. 

unlock_state: Kabelverriegelung Einstellung
0: Verriegeln solange Auto angesteckt
1: Nach Ladevorgang automatisch entriegeln
2: Kabel immer verriegelt lassen

Apparently this state can also be set according to the api docs.

**Comment by cathiele** [comment]
sorry. did not notice this issue until today. this is already possible with the service "set_cable_lock_mode". You have to specify the charger_name and cable_lock_mode with a value like you write it (0,1,2)

Please reopen the issue if it does not work
