### ISSUE TITLE
Calibration for older devices

### ISSUE THREAD

**Issue by eingemaischt** [cathiele/homeassistant-goecharger#61]
The older version of the goecharger often detects a lower voltage - for example 215V while 230V are on the line.
Therefore the energy shown and extracted is about 10% too low.  

I wrote several feature requests to the company, but they do not seem to be interested in fixing this bug in the older version.

So I would like to implement a calibration offset in this integration. 

But: This is only a dirty workaround - if you suffer from the bug, too: Please file a bug at the manufacturer.

**Comment by eingemaischt** [comment]
https://github.com/cathiele/homeassistant-goecharger/pull/63

**Comment by cathiele** [comment]
finally completely working in 0.25.2 i will close this now.
